// <auto-generated />
using System;
using Contacts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contacts.Migrations
{
    [DbContext(typeof(ContactsDbContext))]
    partial class ContactsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Contacts.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("462cdacf-1d2e-49d7-af10-aefad2d29459"),
                            Name = "Służbowy"
                        },
                        new
                        {
                            Id = new Guid("020b977f-e9f0-4310-af8e-1be21fab0a77"),
                            Name = "Prywatny"
                        });
                });

            modelBuilder.Entity("Contacts.Model.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomSubCategory")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("SubCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Contacts.Model.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1a7c6d8-3f44-4c9a-9f1a-111111111111"),
                            CategoryId = new Guid("462cdacf-1d2e-49d7-af10-aefad2d29459"),
                            Name = "Szef"
                        },
                        new
                        {
                            Id = new Guid("b2a7c6d8-3f44-4c9a-9f1a-222222222222"),
                            CategoryId = new Guid("462cdacf-1d2e-49d7-af10-aefad2d29459"),
                            Name = "Sprzedaż"
                        },
                        new
                        {
                            Id = new Guid("b3a7c6d8-3f44-4c9a-9f1a-333333333333"),
                            CategoryId = new Guid("462cdacf-1d2e-49d7-af10-aefad2d29459"),
                            Name = "Kontrahent"
                        },
                        new
                        {
                            Id = new Guid("b4a7c6d8-3f44-4c9a-9f1a-444444444444"),
                            CategoryId = new Guid("462cdacf-1d2e-49d7-af10-aefad2d29459"),
                            Name = "Dział IT"
                        },
                        new
                        {
                            Id = new Guid("c1a7c6d8-3f44-4c9a-9f1a-555555555555"),
                            CategoryId = new Guid("020b977f-e9f0-4310-af8e-1be21fab0a77"),
                            Name = "Rodzina"
                        },
                        new
                        {
                            Id = new Guid("c2a7c6d8-3f44-4c9a-9f1a-666666666666"),
                            CategoryId = new Guid("020b977f-e9f0-4310-af8e-1be21fab0a77"),
                            Name = "Przyjaciele"
                        },
                        new
                        {
                            Id = new Guid("c3a7c6d8-3f44-4c9a-9f1a-777777777777"),
                            CategoryId = new Guid("020b977f-e9f0-4310-af8e-1be21fab0a77"),
                            Name = "Znajomi"
                        },
                        new
                        {
                            Id = new Guid("c4a7c6d8-3f44-4c9a-9f1a-888888888888"),
                            CategoryId = new Guid("020b977f-e9f0-4310-af8e-1be21fab0a77"),
                            Name = "Sąsiedzi"
                        });
                });

            modelBuilder.Entity("Contacts.Model.Contact", b =>
                {
                    b.HasOne("Contacts.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Contacts.Model.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Contacts.Model.SubCategory", b =>
                {
                    b.HasOne("Contacts.Model.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Contacts.Model.Category", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
